### ISSUE TITLE
String format %0.2f crashes the Android app

### ISSUE THREAD

**Issue by hepspl** [skiptools/skip#121]
Hi, I noticed that putting "%0.2f" for string format ends up in Android app crashing.

`let doubleValue = 3.123456
var body: some View {
	Text("\(String(format: "%0.2f", doubleValue))")
}`

After checking StringTests in SkipLibTest I realized I should use "%.2f" instead.
Changing %0.2f to %.2f fixed the issue.

But still: should %0.2f result in app crash?
Reporting just in case if you would like to improve that.

**Comment by marcprux** [comment]
Thanks for the report. I've reproduced it, and we'll work on getting a fix in place. I'll re-assign this issue to the `skip-foundation` repository, since that is the place where the error occurs.

For the record, is is throwing a [MissingFormatWidthException](https://developer.android.com/reference/java/util/MissingFormatWidthException) as seen with `adb logcat` is:

```
05-17 08:28:31.183 10940 10940 E AndroidRuntime: java.util.MissingFormatWidthException: %0.2f
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.checkNumeric(Formatter.java:3283)
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.checkFloat(Formatter.java:3262)
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2983)
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2778)
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at java.util.Formatter.parse(Formatter.java:2711)
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2660)
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2614)
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at java.lang.String.format(String.java:4017)
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at skip.lib.StringKt.invoke(String.kt:406)
05-17 08:28:31.183 10940 10940 E AndroidRuntime: 	at skip.demo.DemoApp$body$1$1$1.invoke(DemoApp.kt:57)

```
