### ISSUE TITLE
iOS App build successfully while android app crashes

### ISSUE THREAD

**Issue by ekahannah** [skiptools/skip#44]
I am building an app using Skip. I can successfully run it on iOS. 
However I encounter a crash on Android. Here is the crash logs:
`
  java.lang.IllegalArgumentException: Type of the key rss.feed.model.RSSItem@a1b47b03 is not supported. On Android you can only use types which can be stored inside the Bundle.
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:78)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazySaveableStateHolder.SaveableStateProvider(LazySaveableStateHolder.kt:84)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt.SkippableItem-JVlU9Rs(LazyLayoutItemContentFactory.kt:134)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt.access$SkippableItem-JVlU9Rs(LazyLayoutItemContentFactory.kt:1)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:101)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:91)
`

Interestingly, I tried to run RSSItem on [playground](https://skip.tools/playground/) and It works fine. here is the swift class file for RSSItem

```
//
//  RSSItem.swift
//
//
//

import Foundation

public struct RSSItem {

    public var title: String
    public var link: String
    public var description: String
    public var enclosure: String
    public var pubDate: String
    public var guid: String
    public var creator: String
    public var content: String
    
    public init(){
        self.title = ""
        self.link = ""
        self.description = ""
        self.enclosure = ""
        self.pubDate = ""
        self.guid = ""
        self.creator = ""
        self.content = ""
    }
    
}

extension RSSItem: Hashable {
    public static func == (lhs: RSSItem, rhs: RSSItem) -> Bool {
        return lhs.title == rhs.title
    }
    public func hash(into hasher: inout Hasher) {
        hasher.combine(title)
    }
    
}
```

 Do you have any idea what may have caused the issue? I am loading the values of RSSItem in a List .

**Comment by ekahannah** [comment]
additionally this is the RSSModel which contains the RSSItem

```
public struct RSSModel {
    public static let title = "title"
    public static let description = "description"
    public static let items = "item"
    
    public var title : String
    public var description: String
    public var items : [RSSItem]
    
    public init() {
        self.title = ""
        self.description = ""
        self.items = []
    }
    
    public init(title: String, description: String, items: [RSSItem]) {
        self.title = title
        self.description = description
        self.items = items
    }
}


extension RSSModel: Hashable {
    public static func == (lhs: RSSModel, rhs: RSSModel) -> Bool {
        return lhs.title == rhs.title
    }
    public func hash(into hasher: inout Hasher) {
        hasher.combine(title)
    }
   
}
```

**Comment by ekahannah** [comment]
Fixed the issue. 

Crash was caused by the id used being \.self which was ambiguous for android.

Error:
```
   List(rssModel.items, id: \.self) { data in
                    NavigationLink(value: data) {
                        rowView(data: data)
                    }
                }
```


Fix: 
```
   List(rssModel.items, id: \.link) { data in
                    NavigationLink(value: data) {
                        rowView(data: data)
                    }
                }
```

**Comment by theedov** [comment]
@marcprux FYI.
I think, this should be handled or at least mentioned in DOCS.

**Comment by marcprux** [comment]
Agreed. I'll re-open this and move it over to the skip-ui repo.
